#pragma once

const char WEB_UPGRADE_TITLE[] = "Upgrade";
const char WEB_UPGRADE_BODY[] =
"    <h1>Firmware Upgrade</h1>\n"
"    <form id=\"upgradeForm\" method=\"post\" action=\"/api/upgrade\">\n"
"        <input type=\"file\" id=\"firmwareFile\" accept=\".bin\" required>\n"
"        <button type=\"submit\">Upload & Upgrade</button>\n"
"    </form>\n"
"    <div id=\"result\"></div>\n"
"    <script>\n"
"    document.getElementById('upgradeForm').onsubmit = function(e) {\n"
"        e.preventDefault();\n"
"        const fileInput = document.getElementById('firmwareFile');\n"
"        if (!fileInput.files.length) {\n"
"            document.getElementById('result').textContent = 'No file selected.';\n"
"            return;\n"
"        }\n"
"        const file = fileInput.files[0];\n"
"        document.getElementById('result').textContent = 'Uploading...';\n"
"        const xhr = new XMLHttpRequest();\n"
"        xhr.open('POST', '/api/upgrade', true);\n"
"        xhr.setRequestHeader('Content-Type', 'application/octet-stream');\n"
"        xhr.upload.onprogress = function(event) {\n"
"            if (event.lengthComputable) {\n"
"                const percent = Math.round((event.loaded / event.total) * 100);\n"
"                document.getElementById('result').textContent = 'Uploading... ' + percent + '%';\n"
"            }\n"
"        };\n"
"        xhr.onload = function() {\n"
"            document.getElementById('result').textContent = xhr.responseText;\n"
"        };\n"
"        xhr.onerror = function() {\n"
"            document.getElementById('result').textContent = 'Upload failed.';\n"
"        };\n"
"        xhr.send(file);\n"
"    };\n"
"    </script>\n";
